version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload # For development with hot-reloading

  electron-app:
    build:
      context: ./electron-app
      dockerfile: Dockerfile
    volumes:
      - ./electron-app:/app
    # For Electron, you might need to expose X server or use VNC/NoVNC for GUI interaction
    # This setup is primarily for building/testing in a headless environment.
    # For local development with GUI, you'd typically run Electron outside Docker
    # or use more advanced X server forwarding.
    environment:
      - DISPLAY=${DISPLAY}
    # If you need to connect to the host's X server (Linux only):
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix
    # network_mode: "host" # Use host network for direct X server access
    depends_on:
      - backend