"""Add openai_api_key to users table

Revision ID: ed9653ba37f7
Revises: 263e8622d397
Create Date: 2025-08-09 00:51:36.925917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed9653ba37f7'
down_revision: Union[str, Sequence[str], None] = '263e8622d397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('openai_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'openai_api_key')
    # ### end Alembic commands ###
